---
- name: Basic Hardening Playbook
  hosts: all
  become: true

  tasks:
    - name: Disable password authentication for SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - { regexp: "^PasswordAuthentication", line: "PasswordAuthentication no" }
        - { regexp: "^ChallengeResponseAuthentication", line: "ChallengeResponseAuthentication no" }

    - name: Disable root login for SSH
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^PermitRootLogin"
        line: "PermitRootLogin no"

    - name: Install unattended-upgrades package
      apt:
        name: unattended-upgrades
        state: present

    - name: Configure unattended upgrades
      lineinfile:
        path: /etc/apt/apt.conf.d/50unattended-upgrades
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - { regexp: "^//Unattended-Upgrade::Automatic-Reboot", line: "Unattended-Upgrade::Automatic-Reboot \"true\";" }
        - { regexp: "^//Unattended-Upgrade::Remove-Unused-Dependencies", line: "Unattended-Upgrade::Remove-Unused-Dependencies \"true\";" }

    - name: Install ufw package
      apt:
        name: ufw
        state: present

    - name: Allow incoming traffic for SSH
      ufw:
        rule: allow
        port: ssh
        proto: tcp
        comment: "Allow SSH traffic"
        state: enabled

    - name: Allow incoming traffic for HTTP
      ufw:
        rule: allow
        port: http
        proto: tcp
        comment: "Allow HTTP traffic"
        state: enabled

    - name: Allow incoming traffic for HTTPS
      ufw:
        rule: allow
        port: https
        proto: tcp
        comment: "Allow HTTPS traffic"
        state: enabled

    - name: Enable ufw firewall
      ufw:
        state: enabled

  handlers:
    - name: Reload firewall
      ufw:
        state: enabled

